### ISSUE TITLE
Verify the signed file

### ISSUE THREAD

**Issue by lehoangnam040** [KarolKlimonczyk/DigitalSignature#1]
Hi, thank you for your tutorial and example code. I have 2 questions about verification of "signed pdf":
- How can I determine that an other file is "signed" by our keystore. I mean someone give me 2 file: "signed by me" and "signed by him", how can I verify that.
- If can, do you have any example code?

Sorry for bad English

**Comment by KarolKlimonczyk** [comment]
Hi, 
glad to hear that I might help you. 
Next time for questions please use my blog [jvmfy.com.](https://jvmfy.com/2018/11/17/how-to-digitally-sign-pdf-files/) Sorry for the late reply but I missed notification. 

All you have to do is load your pdf file and then fetch the signature from it. Then you will be able to check if it is yours or not, by using your Keystore. 

Unfortunately, I don't have any sample code, but I believe that the following code may help you a lot. 

```
Store certStore = cmsSignedData.getCertificates();
SignerInformationStore signers = cmsSignedData.getSignerInfos();
Collection c = signers.getSigners();
Iterator it = c.iterator();

while (it.hasNext()){
  SignerInformation signer = (SignerInformation)it.next();
  Collection certCollection = certStore.getMatches(signer.getSID());
  Iterator certIt = certCollection.iterator();
  X509CertificateHolder cert = (X509CertificateHolder)certIt.next();
  if (signer.verify(new JcaSimpleSignerInfoVerifierBuilder().build(cert))) {
    // successfully verified
  }
}
```

[CODE SOURCE](https://reflectoring.io/how-to-sign/)

If you still have any question, please let me know here in this issue, or on my blog. I'll try to help you.

**Comment by lehoangnam040** [comment]
Thanks you for your help. The verification is done by load public key from Keystore file. Then check the signature in pdf file. I'll closed my issue now.
